---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  name: windows-2012R2

suites:
  - name: default
    run_list:
      - recipe[sourcetree::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
