---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-7
    driver:
      box: aartemjevas/windows7PRO_64-chef
      customize:
        memory: 2048
  - name: windows-81
    driver:
      box: aartemjevas/windows81Pro_64-chef
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[sourcetree::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
